### ISSUE TITLE
Nvidia proprietary issue with GTX 750 ti

### ISSUE THREAD

**Issue by NicTanghe** [instantOS/instantOS#6] opened 2020-05-14 17:48 UTC
No mousecontol or keyboardcontroll after i'm booted into HD os.
also the top bar is way to large and about 3 times the instantoslogo on the left.

**Comment by paperbenni** [comment] 2020-05-14 18:10
Can I have a screenshot? (Can be with a phone if the keyboard doesn't work)
The new arch based build will be out tomorrow, maybe the issue is already fixed there.

**Comment by NicTanghe** [comment] 2020-05-14 18:49
il take a photo witkh my callphone later.
Meanwhile i did notice my keyboard and mouse work for a couple of seconds before they stop working.
it baffles me what can cause this.

could it be that the usb drivers just crash and stop working after a few seconds ?
specs.

cpu; 3950X
gpu: 750Ti
storage: mp600 nvme ssd
motherboard: asus rog 570 gaming.

(i just got my brandnew pc working and i'm dying to get it up and running. stil having shit like this happen all day :/ )

**Comment by paperbenni** [comment] 2020-05-14 22:44
That is really weird. The terminal prompt is also all messed up. 
It could be an issue with the font rendering (and by extension Xorg). 
The new build (based on Arch now) is now out. Let me know if it fixed the issue. 
https://github.com/instantOS/instantOS/releases/download/beta2/instantos_beta_2.iso

**Comment by NicTanghe** [comment] 2020-05-15 09:41
Ok i'll install asap.
Btw i installed plain manjaro and had no issues.
asside from being unable to install nvidea drivers.

**Comment by NicTanghe** [comment] 2020-05-15 15:47
Ok same issues persist. in the new beta.

**Comment by paperbenni** [comment] 2020-05-15 15:56
What exactly do you mean by HD os? The live session? The installed OS?
Is the font still huge? Can you go to tty? Is the display also frozen? (eg does the time in the top right change?)
I'd like you to be a little more precise, some of your sentences are borderline incomprehensible. 
Spending a little more time on spelling will make resolving the issue much easier.

**Comment by paperbenni** [comment] 2020-05-15 16:00
Did the install work?
And how were you unable unable to install NVIDIA drivers? instantOS normally detects NVIDIA cards and automatically installs them. Maybe that's what messed up the install...
You said the PC is brand new. Did the GTX 750 ti ever work? It's a really old card. (and hell of a bottleneck by the way, your CPU is massive)

**Comment by NicTanghe** [comment] 2020-05-15 16:10
i had no prompt for selecting anny nvidia drivers.
by HD os i mean the installed os on my ssd.
the font is stil huge. i will check if the dispay is also frozen.
i think will be.

note installing the propretiery drivers did not work on manjaro. but the open source ones worked.

i just bought the gpu secondhand. and the powersuply is also old.
i could boot into dota in manjora and it showed some opensource drivers as installed .
I don't know which ones tho but since i don't have an apu it should work i think ?
also in windows the nvidia driver worked.



ps. the gpu is temporary until the 3080 arrives.

**Comment by paperbenni** [comment] 2020-05-15 16:21
Ok, I found the solution. The gtx 750 is not supported by NVIDIA anymore!
From the Arch Wiki

> GeForce 7 series cards and older [NV6x, NV4x and lower] do not have a driver packaged for Arch Linux.

This means that you'll be stuck with nouveau (the open source drivers) until your new card arrives. I'll change the installer to install the open source drivers for older cards. 
I'll need the output of
```lspci | grep -i vga```
From the live session for this. Can you boot up the live session and run that really quick?

**Comment by NicTanghe** [comment] 2020-05-15 16:26
ok thx duderino.
if only i'd have known when i bought it well its only for a couple of months annyway so idc.

One lmore thing i think it froze during loading initial ramdisc this time tho.
I hate forcing a shutdown :'(

**Comment by paperbenni** [comment] 2020-05-15 16:41
It's not that bad if your OS install is broken anyway. I'm working on the open source driver prompt, but I still need the ``` lspci | grep -i vga``` output from the live session (not the installed one, just boot from usb and run the command)

**Comment by NicTanghe** [comment] 2020-05-15 17:06
Oh ok i'll do that.
one more thing.
i reinstalled again becouse i got stuck at loading ramdisc before.
Now my whole system simply shuts down after a couple of secs.

**Comment by paperbenni** [comment] 2020-05-15 17:08
Do not reinstall yet, I'm working on fixing the issue. Boot from the live disk and tell me what the output of the ```lspci | grep -i vga``` is please.

**Comment by NicTanghe** [comment] 2020-05-15 17:36
ugh trying to but now etcher is fucking up or something idk.
when i run my newly made usb i get?

uefi
mapping table
fs1 .....
FS3 ....
FS0....

after attemting to find efi i wound up at the installed os grub and had stuck at the loading initial ramdisk again.
Someone up there realy hates me.

**Comment by paperbenni** [comment] 2020-05-15 17:41
You don't need to burn a new usb everytime you want to have a live session. The USB is read only when in the live session, you can use it as many times as you want. Did you burn a new one?

**Comment by paperbenni** [comment] 2020-05-15 17:44
Oooh, I forgot to mention, the installer is largely network based, that means it always uses the newest version. You can use the same live usb and it will always have the newest installer. You don't need to burn a new one every update.

**Comment by paperbenni** [comment] 2020-05-15 17:45
Anyway, the installer now lets you choose between open source and proprietary NVIDIA drivers. If the proprietary drivers don't work (which is the case for your card), select the open source variant during installation.

**Comment by NicTanghe** [comment] 2020-05-15 17:48
i know i din't i just thought some files where missing after being used but it was something else.

annyway the output is.

VGA compatible controller: NVIDIA Corporation GM107 [GeForce GTX 750 Ti] (rev a2)
not sure if 100% tiped corectly but i think so.
gtg eat brb.

**Comment by paperbenni** [comment] 2020-05-15 17:50
Thank you, I just pushed the update. You can try a reinstall now. Remember to choose open source drivers during installation.

**Comment by NicTanghe** [comment] 2020-05-15 18:56
i get script failed during install. then
instalation finished.
no prompt to reboot.

lines that failed i can c . 
bash: /opt/menus/backlight.sh : no such file or directory
cat: /usr/share/instantdotfiles/lightdm-gtk-greeter.conf: No such file or dirctory.

on reboot 
after i enter my password.
i get the error failed to start session.
my keyboard and mouse keep working tho.

I'll atempt a reinstall. and c if it fixes my problem.

**Comment by paperbenni** [comment] 2020-05-15 19:14
That sounds like you lost connection during install. Are you connected via ethernet?

**Comment by NicTanghe** [comment] 2020-05-15 20:14
Hello i ws installing with wifi.
i just connected with cable and evrything is now working perfectly.
typing this from installed instantOS

**Comment by paperbenni** [comment] 2020-05-15 20:28
Nice to hear :)

**Comment by NicTanghe** [comment] 2020-05-18 20:39
Evrywhere is looked it said nvidea was still supporting the 750ti ?
zhere did you get that information ?

**Comment by paperbenni** [comment] 2020-05-19 08:56
You could try installing nvidia-dkms. If the card doesn't do proprietary with other operating systems too, it may be a hardware issue.

**Comment by NicTanghe** [comment] 2020-05-19 10:58
wel it does with windows 10.

when i try to install nvidia-dmks i get the error 
`==> unable to install module nvidia/440.82 for kernel *: Missing kernel headers.`

**Comment by paperbenni** [comment] 2020-05-19 11:02
Have you tried installing ```linux-headers``` and ```linux-lts-headers```

**Comment by NicTanghe** [comment] 2020-05-19 11:07
linux-lts-headers throws an error about a tree or something the linux-headers work.
Probably becouse it's not using lts- kernel ?

**Comment by paperbenni** [comment] 2020-05-19 11:07
then try installing ```linux-lts```

**Comment by NicTanghe** [comment] 2020-05-19 11:13
When installing  linux-lts
Warning about possibly missing firmware modules for wd719x , aic94xx .
I don't think its relevant but hat do i know.

And the nvidia thing seems to have worked.

What next ?

**Comment by paperbenni** [comment] 2020-05-19 11:13
By the way you can take screenshots by doing super + a and typing in sc. You can then paste the screenshot into github issues with Ctrl + V
This is quicker than describing the error

**Comment by paperbenni** [comment] 2020-05-19 11:13
Does the proprietary driver work now?

**Comment by NicTanghe** [comment] 2020-05-19 11:16
Installing/configuring it scares me and id really know how to do it.
also, if I reboot now I lose my only working terminal because the other issue I  made happened.
Can u maybe add the fixes we tried to the installation script while I go grab something to eat and then on b reinstall instandos

**Comment by paperbenni** [comment] 2020-05-19 11:19
I already added the kernel headers, it will also be switching from urxvt to luke-st. I'll add nvidia-dkms to the installer as a choice really quick.

**Comment by paperbenni** [comment] 2020-05-19 11:24
But there's no harm in trying a reboot if you're going to reinstall anyway

**Comment by paperbenni** [comment] 2020-05-19 11:36
Don't reinstall yet, still uploading

**Comment by paperbenni** [comment] 2020-05-19 12:34
Okay, the installer is now updated, you can now try choosing dkms as a driver during installation.

**Comment by NicTanghe** [comment] 2020-05-19 14:01
ok i'l reinstall 1 more time :)

**Comment by NicTanghe** [comment] 2020-05-19 14:08
Hello i tried to reinstall just now but i only had nouveau or none as options i diden't c anny other options so i abborted.

**Comment by paperbenni** [comment] 2020-05-19 14:39
This is fixed now.

**Comment by NicTanghe** [comment] 2020-05-23 11:16
ok i gues it's time for another reinstall then.

**Comment by NicTanghe** [comment] 2020-05-23 12:17
i only get are you sure you do not want to install graphic drivers as an option.

**Comment by paperbenni** [comment] 2020-05-23 12:22
After selecting an option or what do you mean?

**Comment by NicTanghe** [comment] 2020-05-23 13:12
things jsut got allot weirder.
at first it dident seem like it worked just for a minute longer.
then i rebooted and evrything worked for a longer time.
then again the same thing.

all usb's and powerbutton stop working.

**Comment by NicTanghe** [comment] 2020-05-23 13:13
also my top bar is stil to large.

**Comment by paperbenni** [comment] 2020-05-23 13:19
Have you tried changing display resolution? The size of the top bar is hardcoded in pixels, so that shouldn't be happening...

**Comment by NicTanghe** [comment] 2020-05-23 13:25
oh and now my entire system just turned of power.
could'nt turn back on without shutting of main power input.

scared to contineu testing

**Comment by NicTanghe** [comment] 2020-05-23 14:37
i installed with the nouveau drivers again whatever was happening was way to weird for my taste.

**Comment by NicTanghe** [comment] 2020-05-23 19:35
ok so i just installed windos 10 and had the same problem with the usb's failing. but when i did a system repair this fixed it.

**Comment by paperbenni** [comment] 2020-05-23 20:06
The usbs failing? You mean like the usb ports of your MB? I can't follow you. Is the driver issue resolved?

**Comment by NicTanghe** [comment] 2020-05-26 12:09
all of the usb's stop sending or receiving data so i cant input anything on the pc.
the driver issue might be solved but it's stil unworkable on the propretiery driver. its impossable to tell if its still the drivers fault byt it only happens on the propretiery driver.

im on windows now annyway so i cant continue troubleshooting.

**Closed** 2020-10-10 16:35 UTC
