### ISSUE TITLE
Youtube Media control

### ISSUE THREAD

**Issue by Titaniumtown** [instantOS/instantOS#34] opened 2020-06-27 18:50 UTC
Could instantOS implement something simular to gnome's mpris2 or kde's browser integration? So I could use media controls on my keyboard, or on my bluetooth headphones to control my youtube video?
Note: I am not using "instantos" i simply installed the package "instantos" from the repo.

**Comment by paperbenni** [comment] 2020-06-29 14:58
I now added this in. You can use either media buttons if your device has them or super + a and ```vv``` for play/pause ```vp``` for previous track and ```vn``` for next track.

**Comment by Titaniumtown** [comment] 2020-06-29 17:13
thanks! what about using a button from my headphones?

**Comment by paperbenni** [comment] 2020-06-29 17:34
What do these buttons register as on xorg? They might be working already. 
Have you tried?

**Comment by Titaniumtown** [comment] 2020-06-29 17:59
How do i tell?

**Comment by paperbenni** [comment] 2020-06-29 18:19
Just try if the headphone buttons work.

**Comment by paperbenni** [comment] 2020-06-29 18:21
Or to get the xorg events, install xorg-xev and run xev in a terminal. Then press the buttons (don't do anything else, xev logs everything you press or do with your mouse which will clog the terminal) and whatever signal the buttons are sending will appear in the terminal.

**Comment by Titaniumtown** [comment] 2020-07-08 18:13
KeyPress event, serial 29, synthetic NO, window 0x6a00001,
    root 0x1a2, subw 0x0, time 72108691, (672,731), root:(675,766),
    state 0x0, keycode 209 (keysym 0x1008ff31, XF86AudioPause), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x6a00001,
    root 0x1a2, subw 0x0, time 72108697, (672,731), root:(675,766),
    state 0x0, keycode 209 (keysym 0x1008ff31, XF86AudioPause), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

**Comment by Titaniumtown** [comment] 2020-07-08 18:14
It still does nothing in my browser.

**Comment by paperbenni** [comment] 2020-07-08 18:24
Which browser are you using?
Firefox doesn't support such controls, works in brave for me...

**Comment by Titaniumtown** [comment] 2020-07-08 18:52
brave and firefox

**Comment by Titaniumtown** [comment] 2020-07-08 21:35
I just switched to brave, and it doesnt work.

**Comment by paperbenni** [comment] 2020-07-08 22:03
Do you have playerctl installed? And do the headphones, media keys or instantASSIST bindings not work?

**Comment by Titaniumtown** [comment] 2020-07-08 22:33
InstantASSIST still works, but not the buttons on my headphones

**Comment by Titaniumtown** [comment] 2020-07-08 22:34
And playerctl is installed

**Comment by paperbenni** [comment] 2020-07-08 22:36
> KeyPress event, serial 29, synthetic NO, window 0x6a00001,
> root 0x1a2, subw 0x0, time 72108691, (672,731), root:(675,766),
> state 0x0, keycode 209 (keysym 0x1008ff31, XF86AudioPause), same_screen YES,
> XLookupString gives 0 bytes:
> XmbLookupString gives 0 bytes:
> XFilterEvent returns: False
> 
> KeyRelease event, serial 32, synthetic NO, window 0x6a00001,
> root 0x1a2, subw 0x0, time 72108697, (672,731), root:(675,766),
> state 0x0, keycode 209 (keysym 0x1008ff31, XF86AudioPause), same_screen YES,
> XLookupString gives 0 bytes:
> XFilterEvent returns: False

That was very helpful. I just added a binding for that button (at the moment git version only). Do your headphones only have one button?

**Comment by Titaniumtown** [comment] 2020-07-08 22:38
My headphones only have one button that controls the content playing, yes.

**Comment by Titaniumtown** [comment] 2020-07-12 06:23
still doesnt seem to work. any ideas?

**Comment by paperbenni** [comment] 2020-07-12 16:59
I had not pushed the fix yet
> controls the content playing  

That means play/pause right? "control" is pretty vague
Anyway, my attempt to fix the issue is now in the repos, you can update and let me know if it worked

**Comment by Titaniumtown** [comment] 2020-07-12 17:19
yes, play and pause.

**Comment by paperbenni** [comment] 2020-07-29 16:20
Is this fixed?

**Comment by Titaniumtown** [comment] 2020-07-29 16:22
Haven't had time to test, sorry. my laptop needs a new mobo which is in the mail.

**Comment by RubenHetKonijn** [comment] 2020-08-08 14:29
I am having the same problem, and also with firefox, Firefox does support media controls on windows/ubuntu, so it probably also does, please implement this, this is the only thing that is bugging be a lot about instantos

**Comment by paperbenni** [comment] 2020-09-18 20:24
@RubenHetKonijn Firefox currently has this as a flag in about:config
![grafik](https://user-images.githubusercontent.com/15818888/93641979-94665d00-f9fd-11ea-920e-950f49c727ce.png)
Not sure if others have this enabled by default but this makes instantassist work with all sorts of players in firefox

**Comment by paperbenni** [comment] 2020-10-13 20:27
The newest version of firefox now enables this feature by default

**Closed by paperbenni** 2020-10-13 20:27 UTC
