### ISSUE TITLE
Odd behavior on third window

### ISSUE THREAD

**Issue by verajosemanuel** [instantOS/instantOS#59] opened 2020-08-26 14:51 UTC
Hi
Love your minimalistic and "instant" approach to Operative system. Installed on my old secondary laptop and it is astonishing the fast it works.

I have noticed a strange behaviour when opening a third terminal window (or any other third application).
I assume in tiling window managers every new window is forced to get all the available space but there is an empty space below. (see screenshot)

![20200826164534](https://user-images.githubusercontent.com/15836677/91318636-b9c7c880-e7bb-11ea-88a9-6e567b17008b.png)

I know I can reorder windows using toggle layout (mod + ctrl + comma) but this takes more typing.

Thanks a lot for a gorgeous minimal SO

**Comment by paperbenni** [comment] 2020-08-26 14:54
This is because you are using the grid layout which makes every window equal in size so having 3 windows can look odd but it is working as intended. What you probably want is the tiling layout which is activated using super + t

**Comment by verajosemanuel** [comment] 2020-08-26 15:00
thanks

**Comment by paperbenni** [comment] 2020-08-26 15:01
Can I close this?

**Comment by verajosemanuel** [comment] 2020-08-26 15:11
yes of course

**Closed** 2020-08-26 15:32 UTC
